### ISSUE TITLE
No module named 'dnnlib'

### ISSUE THREAD

**Issue by AwesomeLemon** [austinxu87/handsoff#2]
Hi,
I'm having an issue when loading the faces Stylegan2 checkpoint (when running ``python train_label_generator.py --exp experiments/faces_seg.json``):
```
Traceback (most recent call last):
  File "train_label_generator.py", line 277, in <module>
    main(opts)
  File "train_label_generator.py", line 165, in main
    all_feature_maps_train_all, all_mask_train_all, num_data = prepare_data(args, palette)
  File "train_label_generator.py", line 48, in prepare_data
    g_all, _, upsamplers, _, avg_latent = prepare_model(args)
  File "/export/scratch2/data/aleksand/handsoff/handsoff/utils/model_utils.py", line 294, in prepare_model
    checkpoint = torch.load(args['stylegan_checkpoint'])
  File "/export/scratch1/home/aleksand/miniconda3/envs/handsoff_env/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/export/scratch1/home/aleksand/miniconda3/envs/handsoff_env/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
ModuleNotFoundError: No module named 'dnnlib'
```
(Note that I wasn't able to use the exact versions of the libraries from ``requirements.yml`` but I'm not seeing a package there that would include ``dnnlib`` in any case)
Could you tell me what I should try?

**Comment by austinxu87** [comment]
`dnnlib` is an NVIDIA-specific library. See [here](https://github.com/NVlabs/stylegan2-ada-pytorch/tree/main/dnnlib) or [here](https://github.com/podgorskiy/dnnlib)

**Comment by AwesomeLemon** [comment]
From which repo have you taken your Faces Stylegan checkpoint? When I use the pytorch version of the ``dnnlib`` that you linked (https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/dnnlib/), I get 
```
ckpt path:  ./stylegan2-checkpoints/stylegan2-ffhq-config-f.pkl
Traceback (most recent call last):
  File "train_label_generator.py", line 277, in <module>
    main(opts)
  File "train_label_generator.py", line 165, in main
    all_feature_maps_train_all, all_mask_train_all, num_data = prepare_data(args, palette)
  File "train_label_generator.py", line 48, in prepare_data
    g_all, _, upsamplers, _, avg_latent = prepare_model(args)
  File "/export/scratch2/data/aleksand/handsoff/handsoff/utils/model_utils.py", line 294, in prepare_model
    checkpoint = torch.load(args['stylegan_checkpoint'])
  File "/export/scratch1/home/aleksand/miniconda3/envs/handsoff_env/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/export/scratch1/home/aleksand/miniconda3/envs/handsoff_env/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
ModuleNotFoundError: No module named 'dnnlib.tflib'
```
So it seems like the module wants a Tensorflow version of dnnlib, is that correct? If I use another version of dnnlib, the loading still fails because Tensorflow is not installed - should it also be installed, and if so, which version?

Also, not sure if it's important, but the checkpoint link in the ReadMe is a .pkl file, not a .pt file (https://drive.google.com/file/d/1igxv6ZP4TFGe_392B-qnSqXnglTKH5yo/view?usp=share_link)

**Comment by AwesomeLemon** [comment]
The checkpoint was indeed what caused the problem, using checkpoint from the Restyle repo (and Pytorch version of dnnlib) fixed it.
